//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int id_detalle { get; set; }
        public int num_factura { get; set; }
        public int id_servicio { get; set; }
        public int cantidad { get; set; }
        public double precio { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
