//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id_reserva { get; set; }
        public Nullable<double> monto { get; set; }
        public int cantidad_personas { get; set; }
        public System.DateTime dia_hora_inicio { get; set; }
        public System.DateTime dia_hora_fin { get; set; }
        public int id_servicio { get; set; }
        public int id_registro { get; set; }
        public int id_usuario { get; set; }
        public int id_pago { get; set; }
    
        public virtual Registro Registro { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Tipo_pago Tipo_pago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
